### ISSUE TITLE
Nuclei QEMU 2023.10 zve32x/zve64x are not supported

### ISSUE THREAD

**Issue by bigmagic123** [riscv-mcu/qemu#4]
Nuclei QEMU 2023.10 only supports the sub extension zve32f/zve64f/zve64d of the V extension

![image](https://github.com/riscv-mcu/qemu/assets/57786250/8197e2ff-e191-4b53-b9fe-5ace9898b6a9)

but zvf32x/zve64x not supports

**Comment by bigmagic123** [comment]
For more detailed information, please refer to the link

https://gitlab.com/qemu-project/qemu/-/issues/2107

**Comment by fanghuaqi** [comment]
In 2024.06, it will be workaround like this https://github.com/riscv-mcu/qemu/commit/7cddf7f79078337655d23539bf7b18d3f48cc75f
